name: "DOC - Build and deploy"
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "**.yml"
      - "**.md"
      - "**.json"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'oxsecurity/oxsecurity.github.io'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.10.4
      - run: pip install mkdocs-material mdx_truly_sane_lists
      - run: |
          git config --global user.name oxsecurity-bot
          git config --global user.email nicolas.vuillamy@ox.security
      - run: mkdocs gh-deploy --force

 